M48
; DRILL file {KiCad 7.0.2.1-36-g582732918d-dirty-deb11} date Thu Jun  1 11:29:00 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-01T11:29:00+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2.1-36-g582732918d-dirty-deb11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1201
%
G90
G05
T1
X4.1071Y-2.4213
T0
M30
