M48
; DRILL file {KiCad 7.0.2.1-36-g582732918d-dirty-deb11} date Thu Jun  1 11:29:00 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-01T11:29:00+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2.1-36-g582732918d-dirty-deb11
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0421
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X3.937Y-2.3622
X3.937Y-2.4803
T2
X2.4803Y-2.3622
X2.4803Y-2.5
T0
M30
